server:
  port: 8083

spring:
  application:
    name: workflow-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=project_manage;encrypt=false
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver